### ISSUE TITLE
Installation and Config

### ISSUE THREAD

**Issue by mrgalup** [BlueDragonX/dispad#22]
Hi there,

I am trying to install this and run it in order to create the config file, but I am seeing some inconsistencies with the readme and the terminal install on ubuntu 14.04. I am seeing the following:
~/dispad$ autoreconf -i
The program 'autoreconf' can be found in the following packages:
 * autoconf
 * autoconf2.13
Try: sudo apt-get install <selected package>

So I installed autoconf2.13. After doing so, I tried the following two commands which produced:
~/dispad$ ./configure
bash: ./configure: No such file or directory
~/dispad$ make && make install
make: *** No targets specified and no makefile found.  Stop.

My apologies if this is obvious, but I don't see how to run/enable dispad, and I can't locate the config file - ~/.dispad. Any advice would be very appreciated.

Thank you,
Mark

**Comment by BlueDragonX** [comment]
It looks like you forgot to actually call `autoreconf -i`. In any case you'll need to install build-essentials before you can build anything: `sudo apt-get install build-essentials`.

**Comment by mrgalup** [comment]
Hi Ryan,


I did call that, which resulted in the list of autoconfig versions with asterisks before them. I will install build essentials before I try again, but can you assist me regarding the above issue of autoreconf -i please?




Thank you,

Mark 



-- 

Mark Galup   | Producer/Engineer/Mixer, Multi-Instrumentalist
615.788.1969



Recording, Mixing, & Mastering

ReelRecording.com
