### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by mrgalup** [BlueDragonX/dispad#23]
Hello,

I am having further problems installing and building dispad. I installed build-essential have also installed several other packages to help fix some issues that arose, but I am seeing the below issue and I cannot find a solution:

~/dispad$ make && make install
Making all in src
make[1]: Entering directory `/home/mr_g/dispad/src'
gcc  -g -O2   -o dispad conf.o control.o dispad.o listen.o  
dispad.o: In function `cleanup':
/home/mr_g/dispad/src/dispad.c:53: undefined reference to `XCloseDisplay'
dispad.o: In function `xlib_error_handler':
/home/mr_g/dispad/src/dispad.c:69: undefined reference to `XQueryExtension'
/home/mr_g/dispad/src/dispad.c:75: undefined reference to `XGetErrorText'
dispad.o: In function `main':
/home/mr_g/dispad/src/dispad.c:158: undefined reference to `XOpenDisplay'
/home/mr_g/dispad/src/dispad.c:183: undefined reference to `XSetErrorHandler'
conf.o: In function `config_file_parse':
/home/mr_g/dispad/src/conf.c:116: undefined reference to `cfg_init'
/home/mr_g/dispad/src/conf.c:117: undefined reference to `cfg_parse'
/home/mr_g/dispad/src/conf.c:118: undefined reference to `cfg_free'
control.o: In function `control_get_value':
/home/mr_g/dispad/src/control.c:36: undefined reference to `XGetDeviceProperty'
control.o: In function `control_init':
/home/mr_g/dispad/src/control.c:126: undefined reference to `XInternAtom'
/home/mr_g/dispad/src/control.c:130: undefined reference to `XCloseDisplay'
control.o: In function `control_set_value':
/home/mr_g/dispad/src/control.c:47: undefined reference to `XChangeDeviceProperty'
control.o: In function `control_free':
/home/mr_g/dispad/src/control.c:141: undefined reference to `XCloseDevice'
control.o: In function `control_set_value':
/home/mr_g/dispad/src/control.c:47: undefined reference to `XChangeDeviceProperty'
control.o: In function `control_load_devices':
/home/mr_g/dispad/src/control.c:56: undefined reference to `XInternAtom'
/home/mr_g/dispad/src/control.c:59: undefined reference to `XListInputDevices'
/home/mr_g/dispad/src/control.c:67: undefined reference to `XOpenDevice'
/home/mr_g/dispad/src/control.c:73: undefined reference to `XListDeviceProperties'
/home/mr_g/dispad/src/control.c:86: undefined reference to `XFree'
/home/mr_g/dispad/src/control.c:89: undefined reference to `XCloseDevice'
/home/mr_g/dispad/src/control.c:104: undefined reference to `XFreeDeviceList'
/home/mr_g/dispad/src/control.c:104: undefined reference to `XFreeDeviceList'
listen.o: In function `listen_init':
/home/mr_g/dispad/src/listen.c:72: undefined reference to `XGetModifierMapping'
/home/mr_g/dispad/src/listen.c:80: undefined reference to `XFreeModifiermap'
/home/mr_g/dispad/src/listen.c:82: undefined reference to `XQueryKeymap'
listen.o: In function `listen_activity':
/home/mr_g/dispad/src/listen.c:43: undefined reference to `XQueryKeymap'
collect2: error: ld returned 1 exit status
make[1]: *** [dispad] Error 1
make[1]: Leaving directory `/home/mr_g/dispad/src'
make: *** [all-recursive] Error 1

Thanks in advance for your help,
Mark

**Comment by BlueDragonX** [comment]
It looks like you need the xorg development libraries.
